import '../../models/country.dart';

class CountryCodes {
  static const List<Country> all = [
    // ----- AFRICA -----
    Country(name: 'Tanzania', dialCode: '+255', flag: '🇹🇿'),
    Country(name: 'Kenya', dialCode: '+254', flag: '🇰🇪'),
    Country(name: 'Uganda', dialCode: '+256', flag: '🇺🇬'),
    Country(name: 'Rwanda', dialCode: '+250', flag: '🇷🇼'),
    Country(name: 'Burundi', dialCode: '+257', flag: '🇧🇮'),
    Country(name: 'South Africa', dialCode: '+27', flag: '🇿🇦'),
    Country(name: 'Nigeria', dialCode: '+234', flag: '🇳🇬'),
    Country(name: 'Ghana', dialCode: '+233', flag: '🇬🇭'),
    Country(name: 'Egypt', dialCode: '+20', flag: '🇪🇬'),
    Country(name: 'Morocco', dialCode: '+212', flag: '🇲🇦'),
    Country(name: 'Algeria', dialCode: '+213', flag: '🇩🇿'),
    Country(name: 'Tunisia', dialCode: '+216', flag: '🇹🇳'),
    Country(name: 'Libya', dialCode: '+218', flag: '🇱🇾'),
    Country(name: 'Sudan', dialCode: '+249', flag: '🇸🇩'),
    Country(name: 'South Sudan', dialCode: '+211', flag: '🇸🇸'),
    Country(name: 'Ethiopia', dialCode: '+251', flag: '🇪🇹'),
    Country(name: 'Eritrea', dialCode: '+291', flag: '🇪🇷'),
    Country(name: 'Djibouti', dialCode: '+253', flag: '🇩🇯'),
    Country(name: 'Somalia', dialCode: '+252', flag: '🇸🇴'),
    Country(name: 'Comoros', dialCode: '+269', flag: '🇰🇲'),
    Country(name: 'Mauritius', dialCode: '+230', flag: '🇲🇺'),
    Country(name: 'Seychelles', dialCode: '+248', flag: '🇸🇨'),
    Country(name: 'Madagascar', dialCode: '+261', flag: '🇲🇬'),
    Country(name: 'Mozambique', dialCode: '+258', flag: '🇲🇿'),
    Country(name: 'Zambia', dialCode: '+260', flag: '🇿🇲'),
    Country(name: 'Zimbabwe', dialCode: '+263', flag: '🇿🇼'),
    Country(name: 'Malawi', dialCode: '+265', flag: '🇲🇼'),
    Country(name: 'Angola', dialCode: '+244', flag: '🇦🇴'),
    Country(name: 'Namibia', dialCode: '+264', flag: '🇳🇦'),
    Country(name: 'Botswana', dialCode: '+267', flag: '🇧🇼'),
    Country(name: 'Eswatini', dialCode: '+268', flag: '🇸🇿'),
    Country(name: 'Lesotho', dialCode: '+266', flag: '🇱🇸'),
    Country(name: 'Senegal', dialCode: '+221', flag: '🇸🇳'),
    Country(name: 'Mali', dialCode: '+223', flag: '🇲🇱'),
    Country(name: 'Burkina Faso', dialCode: '+226', flag: '🇧🇫'),
    Country(name: 'Niger', dialCode: '+227', flag: '🇳🇪'),
    Country(name: 'Chad', dialCode: '+235', flag: '🇹🇩'),
    Country(name: 'Central African Republic', dialCode: '+236', flag: '🇨🇫'),
    Country(name: 'Cameroon', dialCode: '+237', flag: '🇨🇲'),
    Country(name: 'Equatorial Guinea', dialCode: '+240', flag: '🇬🇶'),
    Country(name: 'Gabon', dialCode: '+241', flag: '🇬🇦'),
    Country(name: 'Congo', dialCode: '+242', flag: '🇨🇬'),
    Country(name: 'Democratic Republic of the Congo', dialCode: '+243', flag: '🇨🇩'),
    Country(name: 'São Tomé and Príncipe', dialCode: '+239', flag: '🇸🇹'),
    Country(name: 'Côte d\'Ivoire', dialCode: '+225', flag: '🇨🇮'),
    Country(name: 'Liberia', dialCode: '+231', flag: '🇱🇷'),
    Country(name: 'Sierra Leone', dialCode: '+232', flag: '🇸🇱'),
    Country(name: 'Guinea', dialCode: '+224', flag: '🇬🇳'),
    Country(name: 'Guinea-Bissau', dialCode: '+245', flag: '🇬🇼'),
    Country(name: 'Cape Verde', dialCode: '+238', flag: '🇨🇻'),
    Country(name: 'Mauritania', dialCode: '+222', flag: '🇲🇷'),
    Country(name: 'The Gambia', dialCode: '+220', flag: '🇬🇲'),
    Country(name: 'Benin', dialCode: '+229', flag: '🇧🇯'),
    Country(name: 'Togo', dialCode: '+228', flag: '🇹🇬'),

    // ----- AMERICAS -----
    Country(name: 'United States', dialCode: '+1', flag: '🇺🇸'),
    Country(name: 'Canada', dialCode: '+1', flag: '🇨🇦'),
    Country(name: 'Mexico', dialCode: '+52', flag: '🇲🇽'),
    Country(name: 'Brazil', dialCode: '+55', flag: '🇧🇷'),
    Country(name: 'Argentina', dialCode: '+54', flag: '🇦🇷'),
    Country(name: 'Colombia', dialCode: '+57', flag: '🇨🇴'),
    Country(name: 'Chile', dialCode: '+56', flag: '🇨🇱'),
    Country(name: 'Peru', dialCode: '+51', flag: '🇵🇪'),
    Country(name: 'Venezuela', dialCode: '+58', flag: '🇻🇪'),
    Country(name: 'Cuba', dialCode: '+53', flag: '🇨🇺'),
    Country(name: 'Dominican Republic', dialCode: '+1', flag: '🇩🇴'),

    // ----- EUROPE -----
    Country(name: 'United Kingdom', dialCode: '+44', flag: '🇬🇧'),
    Country(name: 'Germany', dialCode: '+49', flag: '🇩🇪'),
    Country(name: 'France', dialCode: '+33', flag: '🇫🇷'),
    Country(name: 'Italy', dialCode: '+39', flag: '🇮🇹'),
    Country(name: 'Spain', dialCode: '+34', flag: '🇪🇸'),
    Country(name: 'Portugal', dialCode: '+351', flag: '🇵🇹'),
    Country(name: 'Netherlands', dialCode: '+31', flag: '🇳🇱'),
    Country(name: 'Belgium', dialCode: '+32', flag: '🇧🇪'),
    Country(name: 'Switzerland', dialCode: '+41', flag: '🇨🇭'),
    Country(name: 'Austria', dialCode: '+43', flag: '🇦🇹'),
    Country(name: 'Sweden', dialCode: '+46', flag: '🇸🇪'),
    Country(name: 'Norway', dialCode: '+47', flag: '🇳🇴'),
    Country(name: 'Denmark', dialCode: '+45', flag: '🇩🇰'),
    Country(name: 'Finland', dialCode: '+358', flag: '🇫🇮'),
    Country(name: 'Ireland', dialCode: '+353', flag: '🇮🇪'),
    Country(name: 'Greece', dialCode: '+30', flag: '🇬🇷'),
    Country(name: 'Turkey', dialCode: '+90', flag: '🇹🇷'),
    Country(name: 'Russia', dialCode: '+7', flag: '🇷🇺'),
    Country(name: 'Ukraine', dialCode: '+380', flag: '🇺🇦'),
    Country(name: 'Poland', dialCode: '+48', flag: '🇵🇱'),
    Country(name: 'Czech Republic', dialCode: '+420', flag: '🇨🇿'),
    Country(name: 'Hungary', dialCode: '+36', flag: '🇭🇺'),
    Country(name: 'Romania', dialCode: '+40', flag: '🇷🇴'),
    Country(name: 'Bulgaria', dialCode: '+359', flag: '🇧🇬'),
    Country(name: 'Serbia', dialCode: '+381', flag: '🇷🇸'),

    // ----- ASIA -----
    Country(name: 'India', dialCode: '+91', flag: '🇮🇳'),
    Country(name: 'China', dialCode: '+86', flag: '🇨🇳'),
    Country(name: 'Japan', dialCode: '+81', flag: '🇯🇵'),
    Country(name: 'South Korea', dialCode: '+82', flag: '🇰🇷'),
    Country(name: 'Indonesia', dialCode: '+62', flag: '🇮🇩'),
    Country(name: 'Malaysia', dialCode: '+60', flag: '🇲🇾'),
    Country(name: 'Singapore', dialCode: '+65', flag: '🇸🇬'),
    Country(name: 'Philippines', dialCode: '+63', flag: '🇵🇭'),
    Country(name: 'Vietnam', dialCode: '+84', flag: '🇻🇳'),
    Country(name: 'Thailand', dialCode: '+66', flag: '🇹🇭'),
    Country(name: 'Pakistan', dialCode: '+92', flag: '🇵🇰'),
    Country(name: 'Bangladesh', dialCode: '+880', flag: '🇧🇩'),
    Country(name: 'Sri Lanka', dialCode: '+94', flag: '🇱🇰'),
    Country(name: 'Nepal', dialCode: '+977', flag: '🇳🇵'),
    Country(name: 'Afghanistan', dialCode: '+93', flag: '🇦🇫'),
    Country(name: 'Uzbekistan', dialCode: '+998', flag: '🇺🇿'),
    Country(name: 'Kazakhstan', dialCode: '+7', flag: '🇰🇿'),
    Country(name: 'Saudi Arabia', dialCode: '+966', flag: '🇸🇦'),
    Country(name: 'United Arab Emirates', dialCode: '+971', flag: '🇦🇪'),
    Country(name: 'Qatar', dialCode: '+974', flag: '🇶🇦'),
    Country(name: 'Kuwait', dialCode: '+965', flag: '🇰🇼'),
    Country(name: 'Oman', dialCode: '+968', flag: '🇴🇲'),
    Country(name: 'Yemen', dialCode: '+967', flag: '🇾🇪'),
    Country(name: 'Jordan', dialCode: '+962', flag: '🇯🇴'),
    Country(name: 'Lebanon', dialCode: '+961', flag: '🇱🇧'),
    Country(name: 'Israel', dialCode: '+972', flag: '🇮🇱'),
    Country(name: 'Palestine', dialCode: '+970', flag: '🇵🇸'),
    Country(name: 'Cyprus', dialCode: '+357', flag: '🇨🇾'),
    Country(name: 'Georgia', dialCode: '+995', flag: '🇬🇪'),
    Country(name: 'Armenia', dialCode: '+374', flag: '🇦🇲'),
    Country(name: 'Azerbaijan', dialCode: '+994', flag: '🇦🇿'),

    // ----- OCEANIA -----
    Country(name: 'Australia', dialCode: '+61', flag: '🇦🇺'),
    Country(name: 'New Zealand', dialCode: '+64', flag: '🇳🇿'),
    Country(name: 'Papua New Guinea', dialCode: '+675', flag: '🇵🇬'),
    Country(name: 'Fiji', dialCode: '+679', flag: '🇫🇯'),
    Country(name: 'Samoa', dialCode: '+685', flag: '🇼🇸'),
    Country(name: 'Solomon Islands', dialCode: '+677', flag: '🇸🇧'),
    Country(name: 'Vanuatu', dialCode: '+678', flag: '🇻🇺'),
  ];
}